In [1]:
import numpy as np

In [2]:
np.random.random()  # get random value again and again 

0.3768245885922008

In [3]:
np.random.seed(1)  # seed(1) will return same value after multiple exicution.
np.random.random()

0.417022004702574

In [4]:
np.random.uniform(1,5) # it will return random float value with in a range.

3.8812979737686324

In [5]:
np.random.uniform(1,100,12).reshape(4,3)

array([[ 1.01132311, 30.93092469, 15.52883319],
       [10.14152088, 19.43976093, 35.21051198],
       [40.27997995, 54.34285667, 42.50025693],
       [68.83673054, 21.24077272, 87.9336262 ]])

In [6]:
np.random.randint(1,10)  #give a random integer value with in a given range.

3

In [7]:
np.random.randint(1,10,5) # range 1 to 10 and an array in a size of 5.

array([5, 8, 8, 2, 8])

In [8]:
np.random.randint(1,10,6).reshape(3,2)  # 2D array.

array([[1, 7],
       [8, 7],
       [2, 1]])

In [9]:
a = np.random.randint(1,10,6)
a

array([2, 9, 9, 4, 9, 8])

In [10]:
# find max of this array.
np.max(a)

9

In [11]:
# find min
np.min(a)

2

In [12]:
# find the index of max value in an array.
np.argmax(a)

1

In [13]:
# find the index of min value in an array.
np.argmin(a)

0

In [14]:
a = np.random.randint(1,10,6)
a

array([4, 7, 6, 2, 4, 5])

In [15]:
# change the odd value to -1 in an array.
a[a%2==1]=-1
a

array([ 4, -1,  6,  2,  4, -1])

In [16]:
# change values using where clause.
a = np.random.randint(1,20,6)
a

array([18, 12, 13, 17, 14, 10])

In [17]:
# where(condition,true,false)
out = np.where(a%2==1,-1,a)
out

array([18, 12, -1, -1, 14, 10])

In [18]:
a = np.random.randint(1,50,10)
a

array([19, 16,  1,  5, 26, 48, 35, 24,  8, 27])

In [19]:
# sort the values 
a = np.sort(a)
a

array([ 1,  5,  8, 16, 19, 24, 26, 27, 35, 48])

In [20]:
# percentile

In [21]:
np.percentile(a,30)

13.599999999999998

In [22]:
np.percentile(a,50)

21.5